---
title: "VoC analyses"
date: 6/5/23
output:
    html_document:
        df_print: 'paged'
        toc: true
        toc_float:
            collapsed: false
            smooth_scroll: true
        number_sections: false
        code_download: true
        self_contained: true
---
```{r chunk settings, include = FALSE}
# set chunk settings
knitr::opts_chunk$set(echo = FALSE, 
                      cache = TRUE,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_chunk$set(dpi=600)
```
                      
```{r setup, include=FALSE}
# list all packages required for the analysis
list.of.packages <- c("here", "tidyverse", "afex")

# check if all packages are installed, if not, install them.
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# load all packages 
lapply(list.of.packages, library, character.only = TRUE)

# add theme for plotting
perri_theme <- function () {
  theme(
    panel.border = element_rect(fill = "transparent", color="gray75"),
    panel.background  = element_blank(),
    plot.background = element_blank(), 
    legend.background = element_rect(fill="transparent", colour=NA),
    legend.key = element_rect(fill="transparent", colour=NA),
    line = element_blank(),
    axis.ticks = element_line(color="gray75"),
    text=element_text(family="Avenir"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    strip.background = element_blank(),
    strip.text = element_text(size=12)
  )
}

```

## Load simulated data
```{r load data}
sim_data <- read_csv("RL_modeling/output/posterior_predictive/simData_subParams_twoAlpha_twoBeta_agencyBonus.csv") %>%
    rename(tokenOffer = offer,
           agencyResp = agencyChoice,
           banditResp = banditChoice,
           reward = outcome) %>%
    mutate(agency = case_when(agencyResp == 2 ~ 1,
                              agencyResp == 1 ~ 0),
           correct = case_when(leftBandit == "bandit50a" & banditResp == 1 ~ 1,
                               leftBandit == "bandit50a" & banditResp == 2 ~ 0,
                               leftBandit == "bandit50b" & banditResp == 1 ~ 0,
                               leftBandit == "bandit50b" & banditResp == 2 ~ 1,
               leftBandit == "bandit30" & banditResp == 1 ~ 0,
                               leftBandit == "bandit30" & banditResp == 2 ~ 1,
                               leftBandit == "bandit70" & banditResp == 1 ~ 1,
                               leftBandit == "bandit70" & banditResp == 2 ~ 0,
                               leftBandit == "bandit10" & banditResp == 1 ~ 0,
                               leftBandit == "bandit10" & banditResp == 2 ~ 1,
                               leftBandit == "bandit90" & banditResp == 1 ~ 1,
                               leftBandit == "bandit90" & banditResp == 2 ~ 0),
           condition = case_when(leftBandit == "bandit30" ~ "bandits7030",
                                 leftBandit == "bandit70" ~ "bandits7030",
                                 leftBandit == "bandit90" ~ "bandits9010",
                                 leftBandit == "bandit10" ~ "bandits9010",
                                 leftBandit == "bandit50a" ~ "bandits5050",
                                 leftBandit == "bandit50b" ~ "bandits5050"),
           uoc = case_when(condition=="bandits9010" ~ 9 - (tokenOffer + 5),
                           condition=="bandits7030" ~ 7 - (tokenOffer + 5),
                           condition=="bandits5050" ~ 5 - (tokenOffer + 5))) %>%
    group_by(subID, simID) %>%
    mutate(trial = row_number()) %>%
    ungroup() %>%
    group_by(subID, simID, condition) %>%
    mutate(trialOfCond = row_number()) %>%
    ungroup() %>%
     group_by(subID, simID, condition,tokenOffer) %>% 
    mutate(block=row_number()) %>% 
    ungroup() %>%
    mutate(dataType = "Model Simulation")
    
sim_data$subID <- str_sub(sim_data$subID, end = -5)
```

```{r load real data}
# load data
load("data/vocDataTidy.RData")
banditTask <- banditTask %>%
    mutate(dataType = "Empirical",
           simID = 0)

demo = banditTask %>% distinct(subID, gender, age, zAge, ageGrp)

#merge demographics with simulated data
combined_data <- full_join(demo, sim_data, by = c("subID"))

#merge real data
empirical_data <- banditTask %>% 
    select(subID, gender, age, zAge, ageGrp, simID, leftBandit, rightBandit,
           tokenOffer, agencyResp, banditResp, reward, agency, correct,
           condition, uoc, trial, trialOfCond, block, dataType)

all_data <- rbind(combined_data, empirical_data)
```


## Plot: Proportion optimal machine selections across age groups and trials
```{r plot bandit choices across trials, width = 7, height = 4, unit = "in"}

#plot simulated data
all_data %>% 
  filter(agency==1, condition!="bandits5050") %>% 
  group_by(condition, block, ageGrp, dataType) %>% 
  summarize(pctCorr = mean(correct), 
    se = sd(correct)/sqrt(n())) %>% 
  ggplot(., aes(x=block, y=pctCorr, color=condition)) +
  geom_point() +
    geom_smooth(method = "lm", aes(fill = condition)) +
  geom_hline(yintercept = .5, linetype="dashed") +
  perri_theme() +
  ylab("Proportion Optimal Machine Selections") +
  xlab("Block") +
  facet_grid(cols = vars(ageGrp), rows = vars(dataType)) +
      scale_fill_manual(name="Condition",
                      labels=c("70/30",
                               "90/10"),
                      values=c("#0077b6", "#03045e"), 
                      guide = guide_legend(reverse=TRUE)) +
  scale_color_manual(name="Condition",
                      labels=c("70/30",
                               "90/10"),
                      values=c("#0077b6", "#03045e"),
                     guide = guide_legend(reverse=TRUE)) +
  theme(strip.text = element_text(size=12))
```


# Agency task: Agency decisions 
## Plot: Agency choices by condition
```{r plot agency decisions, fig.height = 4, fig.width = 7, unit = "in"}

# all conditions
ggplot(data=(all_data %>% 
               group_by(condition, block, ageGrp, dataType) %>%
             summarize(m=mean(agency), se= sd(agency/sqrt(n())))),
       aes(x=block, y=m, group=condition, color=condition)) +
  geom_point() +
    geom_smooth(method = "lm", aes(fill = condition)) +
  facet_grid(cols = vars(ageGrp), rows = vars(dataType)) +
  ylim(.4,.8) +
  perri_theme() +
  ylab("Proportion Agency Choices") +
    xlab("Block") +
  scale_fill_manual(name="Condition",
                      labels=c("50/50", 
                               "70/30", 
                               "90/10"),
                      values=c("#00b4d8", "#0077b6", "#03045e"), 
                      guide = guide_legend(reverse=TRUE)) +
  scale_color_manual(name="Condition",
                      labels=c("50/50", 
                               "70/30", 
                               "90/10"),
                      values=c("#00b4d8", "#0077b6", "#03045e"),
                      guide = guide_legend(reverse=TRUE))

```

## Plot: Sensitivity to value of control
```{r VoC plot, fig.height = 4, fig.width = 7, unit = "in"}

VoC_plot_sub_means <- all_data %>% 
    mutate(taskHalf = case_when(trial < 158 ~ "First Half of Task",
                                trial > 157 ~ "Second Half of Task")) %>%
    group_by(ageGrp, taskHalf, uoc, subID, dataType) %>%
    summarize(meanSubAgency = mean(agency, na.rm = T))

VoC_plot_means <- VoC_plot_sub_means %>% 
    group_by(ageGrp, taskHalf, uoc, dataType) %>%
    summarize(meanAgency = mean(meanSubAgency, na.rm = T),
              seAgency = sd(meanSubAgency / sqrt(n())))

#plot
VoC_plot <- ggplot(VoC_plot_means, aes(x = uoc, y = meanAgency, color = ageGrp)) +
      facet_grid(cols = vars(taskHalf), rows = vars(dataType)) +
    geom_point(aes(color = ageGrp)) + 
    geom_errorbar(aes(color = ageGrp, ymin = meanAgency - seAgency, ymax = meanAgency + seAgency), width = .1) + 
    geom_line(aes(group = ageGrp)) +
    perri_theme() + 
    scale_color_manual(values=c("#84347C", "#B40424", "#EB6D1E"), name = "Age Group") +
    xlab("Value of Control (VoC)") +
    ylab("Proportion Agency Choices") +
    geom_hline(yintercept = .5, linetype = "dashed") +
    geom_vline(xintercept = 0, linetype = "dashed")
VoC_plot
```

## Summary stats: Sensitivity to value of control
```{r VoC summary stats}

# What proportion of trials did they choose agency when VoC was 0?
VoC_zero_means_sub <- all_data %>% 
    filter(uoc == 0) %>%
    group_by(ageGrp, subID, dataType) %>%
    summarize(meanSubAgency = mean(agency, na.rm = T))

VoC_zero_means_ageGrp <- VoC_zero_means_sub %>%
    group_by(ageGrp, dataType) %>%
    summarize(meanAgency = mean(meanSubAgency, na.rm = T),
              seAgency = sd(meanSubAgency / sqrt(n())))
VoC_zero_means_ageGrp


VoC_zero_means <- VoC_zero_means_sub %>%
    ungroup() %>%
    summarize(meanAgency = mean(meanSubAgency, na.rm = T),
              seAgency = sd(meanSubAgency / sqrt(n())))
VoC_zero_means

# What was average VoC when participants had 50% chance of choosing agency?
VoC_chance_means_sub <- all_data %>% 
    group_by(ageGrp, subID, uoc, dataType) %>%
    summarize(meanSubAgency = mean(agency, na.rm = T)) 

#identify when 50% line is crossed
VoC_chance_means <- VoC_chance_means_sub %>% 
    group_by(ageGrp, uoc, dataType) %>%
    summarize(meanAgency = mean(meanSubAgency, na.rm = T),
              seAgency = sd(meanSubAgency / sqrt(n()))) %>%
    ungroup() %>%
    group_by(ageGrp, dataType) %>%
    mutate(priorMeanAgency = lag(meanAgency),
           threshold = case_when(meanAgency > .5 & priorMeanAgency < .5 ~ 1)) %>%
    filter(threshold == 1)
VoC_chance_means
```