---
title: "VoC Recoverability"
date: 6/12/23
output:
    html_document:
        df_print: 'paged'
        toc: true
        toc_float:
            collapsed: false
            smooth_scroll: true
        number_sections: false
        code_download: true
        self_contained: true
---
```{r chunk settings, include = FALSE}
# set chunk settings
knitr::opts_chunk$set(echo = FALSE, 
                      cache = TRUE,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_chunk$set(dpi=600)
```
                      
```{r setup, include=FALSE}
# list all packages required for the analysis
list.of.packages <- c("tidyverse", "latex2exp", "patchwork", "ggpubr")

# check if all packages are installed, if not, install them.
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# load all packages 
lapply(list.of.packages, library, character.only = TRUE)

# add theme for plotting
perri_theme <- function () {
  theme(
    panel.border = element_rect(fill = "transparent", color="gray75"),
    panel.background  = element_blank(),
    plot.background = element_blank(), 
    legend.background = element_rect(fill="transparent", colour=NA),
    legend.key = element_rect(fill="transparent", colour=NA),
    line = element_blank(),
    axis.ticks = element_line(color="gray75"),
    text=element_text(family="Avenir"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 15),
    title = element_text(size = 15),
    strip.background = element_blank(),
    strip.text = element_text(size=12)
  )
}

color1 = "#00b4d8"
color2 = "#0077b6"
color3 = "#03045e"

```

# Model recovery
```{r load model recoverability results}

model_recov <- read_csv("RL_modeling/output/recoverability/BIC_recovery.csv") %>%
    pivot_longer(cols = oneAlpha_oneBeta:twoAlpha_twoBeta_agencyBonus,
                 names_to = "sim_model",
                 values_to = "prop")


model_recov$sim_model <- factor(model_recov$sim_model, levels = c("oneAlpha_oneBeta",
                                                                  "oneAlpha_twoBeta",
                                                                  "twoAlpha_oneBeta",
                                                                  "twoAlpha_twoBeta",
                                                                  "oneAlpha_oneBeta_agencyBonus",
                                                                  "oneAlpha_twoBeta_agencyBonus",
                                                                  "twoAlpha_oneBeta_agencyBonus",
                                                                  "twoAlpha_twoBeta_agencyBonus"),
                                labels = c(
                                     TeX("$one\\alpha\\_one\\beta$"), 
                                    TeX("$one\\alpha\\_two\\beta$"),
                                    TeX("$two\\alpha\\_one\\beta$"),
                                    TeX("$two\\alpha\\_two\\beta$"), 
                                    TeX("$one\\alpha\\_one\\beta$_agency"), 
                                    TeX("$one\\alpha\\_two\\beta$_agency"),
                                    TeX("$two\\alpha\\_one\\beta$_agency"),
                                    TeX("$two\\alpha\\_two\\beta$_agency")))

model_recov$RecoveredModel <- factor(model_recov$RecoveredModel, levels = c("oneAlpha_oneBeta",
                                                                  "oneAlpha_twoBeta",
                                                                  "twoAlpha_oneBeta",
                                                                  "twoAlpha_twoBeta",
                                                                  "oneAlpha_oneBeta_agencyBonus",
                                                                  "oneAlpha_twoBeta_agencyBonus",
                                                                  "twoAlpha_oneBeta_agencyBonus",
                                                                  "twoAlpha_twoBeta_agencyBonus"),
                                labels = c(
                                    TeX("$one\\alpha\\_one\\beta$"), 
                                    TeX("$one\\alpha\\_two\\beta$"),
                                    TeX("$two\\alpha\\_one\\beta$"),
                                    TeX("$two\\alpha\\_two\\beta$"), 
                                    TeX("$one\\alpha\\_one\\beta$_agency"), 
                                    TeX("$one\\alpha\\_two\\beta$_agency"),
                                    TeX("$two\\alpha\\_one\\beta$_agency"),
                                    TeX("$two\\alpha\\_two\\beta$_agency")))


                                                         
```

```{r BIC confusion matrix, fig.width = 8, fig.height = 5, units = "in"}

bic_confusion_plot <- ggplot(model_recov, aes(x = sim_model, y = RecoveredModel)) +
    geom_tile(aes(fill = prop)) +
    geom_text(aes(label=round(prop, 2)), color = "white") +
    perri_theme() +
    xlab("Simulated Model") +
    ylab("Fitted Model") +
    scale_y_discrete(labels = parse(text = levels(model_recov$RecoveredModel))) +
    scale_x_discrete(labels = parse(text = levels(model_recov$sim_model))) +
    scale_fill_continuous(type = "gradient", name = "p(fit model | sim model)") +
    theme(axis.text.x = element_text(angle = 75, hjust = 1))
bic_confusion_plot   
    
```

```{r BIC inversion matrix, fig.width = 8, fig.height = 5, units = "in"}

#determine the total number of participants best-fit by a given model
prop_sums <- model_recov %>%
    group_by(RecoveredModel) %>%
    summarize(propSum = sum(prop))

temp <- full_join(model_recov, prop_sums, by = c("RecoveredModel"))

#determine the number of participants best-fit by a given model, generated by that model
temp$inversionProp <- temp$prop / temp$propSum

bic_inversion_plot <- ggplot(temp, aes(x = sim_model, y = RecoveredModel)) +
    geom_tile(aes(fill = inversionProp)) +
    geom_text(aes(label=round(inversionProp, 2)), color = "white") +
    perri_theme() +
    xlab("Simulated Model") +
    ylab("Fitted Model") +
    scale_y_discrete(labels = parse(text = levels(model_recov$RecoveredModel))) +
    scale_x_discrete(labels = parse(text = levels(model_recov$sim_model))) +
    scale_fill_continuous(type = "gradient", name = "p(sim model | fit model)") +
    theme(axis.text.x = element_text(angle = 75, hjust = 1))
bic_inversion_plot   
    
```

```{r combined confusion inversion, fig.width = 16, fig.height = 5, units = "in"}
bic_recov = bic_confusion_plot + bic_inversion_plot
bic_recov
```

# Parameter recovery 
```{r parameter recovery}

sim_params <- read_csv("RL_modeling/output/recoverability/twoAlpha_twoBeta_agencyBonus_sim_params.csv") %>%
    rownames_to_column(var = "simID") %>%
    pivot_longer(cols = alphaChoice:agencyBonus,
                 names_to = "param",
                 values_to = "sim_val")


fit_params <- read_csv("RL_modeling/output/recoverability/twoAlpha_twoBeta_agencyBonus_fit_params.csv") %>%
     rownames_to_column(var = "simID") %>%
      pivot_longer(cols = alphaChoice:agencyBonus,
                 names_to = "param",
                 values_to = "fit_val")

#combine
param_recov <- full_join(sim_params, fit_params, by = c("param", "simID"))

param_recov$param <- factor(param_recov$param, labels = c("Agency~Bonus", 
                                                           TeX("$\\alpha_{choice}$"), 
                                                           TeX("$\\alpha_{comp}$"), 
                                                           TeX("$\\beta_{agency}$"), 
                                                           TeX("$\\beta_{machine}$")))

```


```{r parameter recovery plot}
param_recov_plot <- ggplot(param_recov, aes(x = sim_val, y = fit_val)) +
    facet_wrap(~param, scales = "free", labeller = label_parsed) +
    geom_point(color = color1,  alpha = .3, size = .5) +
    geom_smooth(method = "lm", color = color2, fill = color2) +
    stat_cor(aes(label = ..r.label..), label.y.npc="top", label.x.npc = "left", method = "pearson",size= 4) + 
    xlab("Simulated Value") +
    ylab("Fitted Value") +
    perri_theme()
param_recov_plot  
```